export const pokedexName = {
  kanto: "Kanto",
  "letsgo-kanto": "Let's Go Kanto",
  "original-johto": "Original Johto",
  "updated-johto": "Updated Johto",
  hoenn: "Hoenn",
  "updated-hoenn": "Updated Hoenn",
  "original-sinnoh": "Original Sinnoh",
  "extended-sinnoh": "Updated Sinnoh",
  "original-unova": "Original Unova",
  "updated-unova": "Updated Unova",
  "kalos-central": "Kalos Central",
  "kalos-coastal": "Kalos Coastal",
  "kalos-mountain": "Kalos Mountain",
  "original-alola": "Original Alola",
  "original-melemele": "Original Melemele",
  "original-akala": "Original Akala",
  "original-ulaula": "Original Ulaula",
  "original-poni": "Original Poni",
  "updated-alola": "Updated Alola",
  "updated-melemele": "Updated Melemele",
  "updated-akala": "Updated Akala",
  "updated-ulaula": "Updated Ulaula",
  "updated-poni": "Updated Poni",
  galar: "Galar",
  "isle-of-armor": "Isle of Armor",
  "crown-tundra": "Crown Tundra",
};
